Connected to pydev debugger (build 131.339)
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python "/Applications/PyCharm CE.app/helpers/pydev/pydevd.py" --multiproc --client 127.0.0.1 --port 60801 --file /Users/zhujialai/devssd/root/repos/CrushAnalysis/main.py
pydev debugger: process 17856 is connecting

JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue*) ;
Processing 20140120...
got symbolicator for /Users/zhujialai/devssd/root/repos/CrushAnalysis/archive/ksmobilebrowser.app/ksmobilebrowser, base address 4000
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ;
JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue*) ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WTF::fastFree(void*) ;
WebCore::Document::styleResolverChanged(WebCore::StyleResolverUpdateFlag) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::ResourceHandle::create(WebCore::NetworkingContext*, WebCore::ResourceRequest const&, WebCore::ResourceHandleClient*, bool, bool) ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadScheduler::HostInformation*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleSubresourceLoad(WebCore::Frame*, WebCore::CachedResource*, WebCore::ResourceRequest const&, WebCore::ResourceLoadPriority, WebCore::ResourceLoaderOptions const&) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ;
HostBase::lock() ;
DispatchHost::performInvocation(void const*) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
HostBase::lock() ;
DispatchHost::performInvocation(void const*) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ;
WebCore::CachedResource::unregisterHandle(WebCore::CachedResourceHandleBase*) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::CachedResource::removeClient(WebCore::CachedResourceClient*) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
SogouIMENameSpace::t_shareMem::t_shareMem() ;
SogouIMENameSpace::t_shareMem::t_shareMem() ;
SogouIMENameSpace::t_shareMem::t_shareMem() ;
CMacIniParse::CMacIniParse() ;
CMacIniParse::CMacIniParse() ;
CMacIniParse::CMacIniParse() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goForward() ;
WebCore::Frame::setView(WTF::PassRefPtr<WebCore::FrameView>) ;
WebCore::DocumentLoader::dataReceived(WebCore::CachedResource*, char const*, int) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadPriority) ;
WebCore::DocumentLoader::dataReceived(WebCore::CachedResource*, char const*, int) ;
WebCore::ResourceLoader::init(WebCore::ResourceRequest const&) ;
WebCore::ResourceLoader::init(WebCore::ResourceRequest const&) ;
WebCore::SubresourceLoader::startLoading() ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadScheduler::HostInformation*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleLoad(WebCore::ResourceLoader*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleSubresourceLoad(WebCore::Frame*, WebCore::SubresourceLoaderClient*, WebCore::ResourceRequest const&, WebCore::ResourceLoadPriority, WebCore::SecurityCheckPolicy, bool, bool, WTF::String const&, bool) ;
WebCore::CachedResourceRequest::load(WebCore::CachedResourceLoader*, WebCore::CachedResource*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedResourceLoader::load(WebCore::CachedResource*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedResource::load(WebCore::CachedResourceLoader*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedImage::load(WebCore::CachedResourceLoader*) ;
WebCore::CachedResourceLoader::loadResource(WebCore::CachedResource::Type, WebCore::KURL const&, WTF::String const&, WebCore::ResourceLoadPriority) ;
WebCore::CachedResourceLoader::requestResource(WebCore::CachedResource::Type, WTF::String const&, WTF::String const&, WebCore::ResourceLoadPriority, bool) ;
WebCore::CachedResourceLoader::requestImage(WTF::String const&) ;
WebCore::ImageLoader::updateFromElement() ;
WebCore::HTMLImageElement::parseMappedAttribute(WebCore::Attribute*) ;
WebCore::StyledElement::attributeChanged(WebCore::Attribute*, bool) ;
WebCore::NamedNodeMap::addAttribute(WTF::PassRefPtr<WebCore::Attribute>) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
(anonymous namespace)::AutoreleasePoolPage::pop(void*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::ResourceHandle::create(WebCore::NetworkingContext*, WebCore::ResourceRequest const&, WebCore::ResourceHandleClient*, bool, bool) ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadScheduler::HostInformation*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleSubresourceLoad(WebCore::Frame*, WebCore::CachedResource*, WebCore::ResourceRequest const&, WebCore::ResourceLoadPriority, WebCore::ResourceLoaderOptions const&) ;
cant resolve offset 0x009f7d25 
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
HostBase::lock() ;
DispatchHost::performInvocation(void const*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::DocumentLoader::dataReceived(WebCore::CachedResource*, char const*, int) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
(anonymous namespace)::AutoreleasePoolPage::pop(void*) ;
HostBase::lock() ;
DispatchHost::performInvocation(void const*) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
(anonymous namespace)::AutoreleasePoolPage::pop(void*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::setDefersLoading(bool) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::FrameLoader::init() ;
(anonymous namespace)::AutoreleasePoolPage::pop(void*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::FrameLoader::init() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::FrameLoader::init() ;
WebCore::InlineBox::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&, WebCore::LayoutUnit, WebCore::LayoutUnit) ;
WebCore::FrameLoader::init() ;
WebCore::DocumentLoader::commitData(char const*, unsigned long) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
(anonymous namespace)::AutoreleasePoolPage::pop(void*) ;
JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue*) ;
WTF::equal(WTF::StringImpl const*, WTF::StringImpl const*) ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::ResourceLoader::init(WebCore::ResourceRequest const&) ;
WebCore::ResourceLoader::init(WebCore::ResourceRequest const&) ;
WebCore::SubresourceLoader::startLoading() ;
WebCore::ResourceLoadScheduler::servePendingRequests(WebCore::ResourceLoadScheduler::HostInformation*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleLoad(WebCore::ResourceLoader*, WebCore::ResourceLoadPriority) ;
WebCore::ResourceLoadScheduler::scheduleSubresourceLoad(WebCore::Frame*, WebCore::SubresourceLoaderClient*, WebCore::ResourceRequest const&, WebCore::ResourceLoadPriority, WebCore::SecurityCheckPolicy, bool, bool, WTF::String const&, bool) ;
WebCore::CachedResourceRequest::load(WebCore::CachedResourceLoader*, WebCore::CachedResource*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedResourceLoader::load(WebCore::CachedResource*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedResource::load(WebCore::CachedResourceLoader*, bool, WebCore::SecurityCheckPolicy, bool) ;
WebCore::CachedImage::load(WebCore::CachedResourceLoader*) ;
WebCore::CachedResourceLoader::loadResource(WebCore::CachedResource::Type, WebCore::KURL const&, WTF::String const&, WebCore::ResourceLoadPriority) ;
WebCore::CachedResourceLoader::requestResource(WebCore::CachedResource::Type, WTF::String const&, WTF::String const&, WebCore::ResourceLoadPriority, bool) ;
WebCore::CachedResourceLoader::requestImage(WTF::String const&) ;
WebCore::ImageLoader::updateFromElement() ;
WebCore::HTMLImageElement::parseMappedAttribute(WebCore::Attribute*) ;
WebCore::StyledElement::attributeChanged(WebCore::Attribute*, bool) ;
WebCore::NamedNodeMap::addAttribute(WTF::PassRefPtr<WebCore::Attribute>) ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ;
WebCore::FrameLoader::init() ;
WebCore::FrameLoader::init() ;
WebCore::Page::goToItem(WebCore::HistoryItem*, WebCore::FrameLoadType) ;
WebCore::Page::goBack() ;
WebCore::Document::settings() const ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderBox::computeRectForRepaint(WebCore::RenderBoxModelObject*, WebCore::IntRect&, bool) ;
WebCore::RenderReplaced::clippedOverflowRectForRepaint(WebCore::RenderBoxModelObject*) ;
WebCore::RenderObject::repaint(bool) ;
WebCore::ImageQualityController::highQualityRepaintTimerFired(WebCore::Timer<WebCore::ImageQualityController>*) ;
